from enum import Enum
class Status(Enum):
    ACTIVE = 'ACTIVE'
    IN_PROGRESS = 'IN PROGRESS'
    IN_PROGRESS_REMOTE_FILE_COPIED ='IN PROGRESS REMOTE COPY DONE'
    COMPLETED_NO_ZIP='COMPLETED NO ZIP'
    EXPIRED = 'EXPIRED'
    DISABLED = 'DISABLED'
